### ISSUE TITLE
Peripherals connected to network without modem

### ISSUE THREAD

**Issue by crazyvinvin** [JheffersonMarques/MorePeripherals#23] opened 2023-06-25 20:30 UTC
Hey there, we found an issue with the peripherals connection to networks. We attachted a modem to a peripheral (in this case a turtle) and laid down a cable next to the computer, the computer sees this cable as a computer. Here are some images:

![image](https://github.com/JheffersonMarques/MorePeripherals/assets/72987554/8eb2180a-5d1b-4ad3-b810-a30a715258bf)
![image](https://github.com/JheffersonMarques/MorePeripherals/assets/72987554/7ae8475c-bef2-47ac-9ca0-e44fb85bb22c)

When a modem is connected, this causes the computer to detect all peripherals on the network twice:
![image](https://github.com/JheffersonMarques/MorePeripherals/assets/72987554/96a4e77f-b6ba-4018-8e5a-5f5eb37397f9)
![image](https://github.com/JheffersonMarques/MorePeripherals/assets/72987554/0ebbd9a7-4a70-4c48-b422-07d1aa86fd75)

We also created an issue at the cc tweaked github page:
https://github.com/cc-tweaked/CC-Tweaked/issues/1498

They also found the problem in the more peripherals mod and suggested a fix.

Many thanks,
MCS Development

PS:
Do you have any discord servers or twitter accs with updates about releases (in particularly 1.19.2 😉 )?

**Comment by OHakimen** [comment] 2023-06-26 15:11
Hello, the code they reference is the cause of the issue, i was trying to dynamically allow peripherals to be recognised as such without registering them one by one, i didn't know it would cause problems, i'm working on a fix rn

**Comment by OHakimen** [comment] 2023-06-26 15:52
Fixed in dev (i'm gonna roll out an update today)

and also responding to your PS, i currently don't post much about my modding anywere, mostly i do stuff and roll a version out, i'm present on the Minecraft Computer Mods Discord server tho, with the handle @hakimen

**Closed as completed** 2023-06-26 16:13 UTC
Labels: bug

**Comment by crazyvinvin** [comment] 2023-06-26 17:52
Thank you so much!
